stages:
  - build
  - linter
  - test
  - deploy-staging
  - deploy-production

#Шаблоны для ветки main
.build-template-main:
  script:
    - docker build -t app:latest .

.linter-template-main:
  script:
    - docker run --rm -d app:latest dotnet format --check
  needs:
    - build-job-main

.test-template-main:
  script:
    - docker run --rm -d app:latest dotnet test
  artifacts:
    paths:
      - ./Dockerfile
    when: on_success
    expire_in: 30 days
  needs:
    - linter-job-main

.deploy-template-main:
  script:
    - docker-compose up -d
  environment:
    name: production
  needs:
    - test-job-main

#ветка main
build-job-main:
  stage: build
  extends: .build-template-main
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

linter-job-main:
  stage: linter
  extends: .linter-template-main
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

test-job-main:
  stage: test
  extends: .test-template-main
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

deploy-production:
  stage: deploy-production
  extends: .deploy-template-main
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
