stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker build -t app:latest .

test-job:
  stage: test
  script: 
#    - -s -v вроде бы для логов
    - docker run -d --rm app:latest dotnet test -s -v

deploy-job:
  stage: deploy
  script:
    - docker-compose up -d