stages:
  - build
  - test
  - deploy
  - notify

variables:
  APP_VERSION: "1.0.0" #временно

build-job:
  stage: build
  script:
    - docker build -t app:latest .

test-job:
  stage: test
  script:
    - docker run -d --rm app:latest dotnet test -s -v
  artifacts:
    paths:
      - ./Dockerfile
    when: on_success
    expire_in: 30 days

deploy-job:
  stage: deploy
  script:
    - docker-compose up -d
  dependencies:
    - test-job

notify-discord:
  stage: notify
  script:
    - |
      if [ "$CI_JOB_STATUS" == "success" ]; then
        STATUS="**УСПЕШНО** ✅"
        COLOR=3066993
      else
        STATUS="**НЕУДАЧНО** ❌"
        COLOR=15158332
      fi
      PAYLOAD=$(cat <<EOF
      {
        "content": "## Деплой приложения завершен!",
        "embeds": [
          {
            "title": "Статус джобы",
            "description": "${STATUS}\n\n**Версия приложения:** \`${APP_VERSION}\`\n**Проект:** ${CI_PROJECT_NAME}\n**Пайплайн:** [#${CI_PIPELINE_IID}](${CI_PIPELINE_URL})",
            "color": ${COLOR}
          }
        ]
      }
      EOF
      )
      curl -X POST -H "Content-Type: application/json" -d "${PAYLOAD}" "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_COMMIT_TAG'